services:
  database:
    image: 'postgres:16.1-alpine'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 5s
      interval: 10s
      retries: 3
    restart: unless-stopped
    container_name: cars_database
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_MASTER_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_MASTER_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  application:
    container_name: application
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    links:
      - "database:db"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DB_MASTER_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_MASTER_PASSWORD}

volumes:
  postgres:
